# Generated by Django 6.0 on 2026-01-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField()),
                ('mindestpreis', models.DecimalField(decimal_places=2, max_digits=8)),
                ('auktionsdauer', models.DurationField(help_text='Dauer der Auktion (z. B. 7 Tage)')),
                ('anzahlListungen', models.PositiveSmallIntegerField(default=1)),
                ('istArchiviert', models.BooleanField(default=False)),
                ('erstelltAm', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
