# Generated by Django 6.0 on 2026-01-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produkte',
            new_name='Produkt',
        ),
    ]
