# Generated by Django 6.0 on 2026-01-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0002_rename_produkte_produkt'),
        ('profil', '0002_alter_review_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='produkt',
            options={'ordering': ['-erstelltAm'], 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkte'},
        ),
        migrations.AddField(
            model_name='produkt',
            name='bild',
            field=models.ImageField(blank=True, help_text='Produktbild (optional)', null=True, upload_to='product/images/'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='verkaeufer_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produkte', to='profil.userprofile'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='anzahlListungen',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='Interner Counter - wird automatisch erhöht'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='produkte', to='produkt.tag'),
        ),
    ]
