# Generated by Django 5.2.10 on 2026-01-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0003_alter_produkt_id'),
        ('produkt', '0003_tag_alter_produkt_options_produkt_bild_and_more'),
    ]

    operations = [
    ]
