# Generated by Django 5.2.10 on 2026-01-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0004_merge_20260112_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
