# Generated by Django 6.0 on 2026-01-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0007_alter_produkt_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='anzahlListungen',
            field=models.PositiveSmallIntegerField(default=1, editable=False, help_text='Wie oft das Produkt insgesamt gelistet wurde'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
