# Generated by Django 5.2.10 on 2026-01-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0008_alter_produkt_anzahllistungen_alter_produkt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
