# Generated by Django 6.0 on 2026-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0008_alter_produkt_anzahllistungen_alter_produkt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='auktionsdauer',
            field=models.DurationField(help_text='Dauer der Auktion'),
        ),
    ]
