# Generated by Django 5.2.10 on 2026-01-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0009_alter_produkt_auktionsdauer'),
        ('produkt', '0009_alter_produkt_id_alter_tag_id'),
    ]

    operations = [
    ]
