# Generated by Django 5.2.10 on 2026-01-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0011_alter_produkt_id_alter_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='gemeldet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
