# Generated by Django 5.2.10 on 2026-01-12 15:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('user_type', models.CharField(choices=[('K', 'Käufer'), ('V', 'Verkäufer'), ('B', 'Beides')], default='K', max_length=1)),
                ('erstellt_am', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profil',
                'verbose_name_plural': 'User Profile',
                'ordering': ['user_type', 'username'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sterne', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('text', models.TextField()),
                ('erstellt_am', models.DateField(default=datetime.date.today)),
                ('gemeldet', models.BooleanField(default=False)),
                ('bewertender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bewerteter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profil.userprofile')),
            ],
            options={
                'verbose_name': 'Bewertung',
                'verbose_name_plural': 'Bewertungen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
