# Generated by Django 5.2.10 on 2026-01-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_alter_review_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='bewertender',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='bewerteter',
            new_name='profile',
        ),
    ]
