# Generated by Django 5.2.10 on 2026-01-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_rename_bewertender_review_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
