# Generated by Django 5.2.10 on 2026-01-13 12:55

import profil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Hausnummer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=profil.models.user_directory_path),
        ),
    ]
