# Generated by Django 5.2.10 on 2026-01-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_alter_review_id_alter_reviewvote_id_and_more'),
        ('profil', '0008_userprofile_house_number_userprofile_profile_picture'),
    ]

    operations = [
    ]
