# Generated by Django 6.0 on 2026-01-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_merge_20260113_1602'),
        ('profil', '0010_alter_review_id_alter_reviewvote_id_and_more'),
    ]

    operations = [
    ]
