# Generated by Django 5.2.10 on 2026-01-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0015_remove_supportrequest_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='closed',
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('answered', 'Beantwortet'), ('closed', 'Geschlossen')], default='open', max_length=20),
        ),
    ]
