# Generated by Django 5.2.10 on 2026-01-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0016_remove_supportrequest_closed_supportrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('answered', 'Beantwortet'), ('closed', 'Geschlossen')], default='open', max_length=10),
        ),
    ]
