# Generated by Django 5.2.10 on 2026-01-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebot', '0007_alter_gebot_id'),
        ('profil', '0021_alter_review_id_alter_reviewvote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='gebot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gebot.gebot'),
        ),
    ]
