# Generated by Django 6.0 on 2026-01-13 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produkt', '0008_alter_produkt_anzahllistungen_alter_produkt_id_and_more'),
        ('profil', '0012_alter_review_id_alter_reviewvote_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biethoehe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('erstelltAm', models.DateTimeField(auto_now_add=True)),
                ('bieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gebote', to='profil.userprofile')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gebote', to='produkt.produkt')),
            ],
            options={
                'verbose_name': 'Gebot',
                'verbose_name_plural': 'Gebote',
                'ordering': ['-biethoehe'],
            },
        ),
    ]
