# Generated by Django 6.0 on 2026-01-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebot', '0004_alter_gebot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gebot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
