# Generated by Django 6.0 on 2026-01-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebot', '0005_alter_gebot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebot',
            name='kauf_bestaetigt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gebot',
            name='kauf_bestaetigt_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
