# Generated by Django 5.2.10 on 2026-01-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebot', '0007_alter_gebot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebot',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gebot',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gebot',
            name='house_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='gebot',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gebot',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
