# Generated by Django 5.2.10 on 2026-01-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gebot', '0008_gebot_city_gebot_country_gebot_house_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gebot',
            name='city',
        ),
        migrations.RemoveField(
            model_name='gebot',
            name='country',
        ),
        migrations.RemoveField(
            model_name='gebot',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='gebot',
            name='street',
        ),
        migrations.RemoveField(
            model_name='gebot',
            name='zip_code',
        ),
    ]
