# Generated by Django 6.0 on 2026-01-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebot', '0009_remove_gebot_city_remove_gebot_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gebot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
