# Generated by Django 5.2.10 on 2026-01-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebot', '0014_alter_gebot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gebot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
